### ISSUE TITLE
Create JSON schema

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#1]

**Comment by ilyalyo** [comment]
@fulldecent Can you please provide more description for this issue?

**Comment by fulldecent** [comment]
Structured Acceptance Test describes a JSON file format. A more formal way to describe a JSON file format is JSON Schema (http://json-schema.org/).

Please create a JSON Schema for our format.

**Comment by ilyalyo** [comment]
Add a PR https://github.com/fulldecent/structured-acceptance-test/pull/11

**Comment by fulldecent** [comment]
Looks good, accepted, thank you.
