### ISSUE TITLE
Create Ruby data structure

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#15]
This work will go in a new `implementations/ruby` folder. Eventually this may moved to a new repository.

 - [x] Create STAT data structures that Ruby programs can use
 - [x] The data structures should support all required and optional parameters designated in the specification
 - [x] It should be extensible

Also, please read the specification regarding incremental output. Please add three methods that allow incremental output:

 - [x] PRINT HEADER -- prints from the beginning of the output (`{`) up to the first finding (`"findings":[`), ends with a new line, and flushes output
 - [x] PRINT FINDING -- prints one finding, ends with a new line and flushes output
 - [x] PRINT FOOTER -- prints the matching `]` and `}` and flushes output

Then when this is done:

 - [x] Make a Gemfile so that people can use this data structure in their projects
 - [x] Publish this Gemfile in Rubygems so everyone can use it

Incremental reading will be added to this data structure in a separate issue.

**Comment by ilyalyo** [comment]
About PRINT HEADER, PRINT FINDING.. For what cases do you need this?
I think it would be better to have one method, for example to_json, which will generate all output at once.

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/structured-acceptance-test/pull/20

**Comment by fulldecent** [comment]
to_json is great for printing everything all at once. But a major feature of STAT is that it is a streaming protocol. This allows it to output in realtime as findings are being made.

See also https://github.com/codeclimate/spec which is nearly one-to-one compatible with the STAT reporting format. Code Climate's spec format is also providing streaming.

So if a `gcc` compiler is running and outputting stat format, then a text editor can begin displaying the compilation errors before the entire file is finished processing.

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/structured-acceptance-test/pull/21

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/structured-acceptance-test/pull/23

**Comment by ilyalyo** [comment]
About this point: Update all programs in the tools/ directory to use this data structure
junit-stat-converter tool use new data structure
stat-validator doesn't need this, it's only validate filecontent against our json schema
stat-reader can be updated,
also I think we can update this repos:
https://github.com/mcandre/lili
https://github.com/mcandre/gtdlint
https://github.com/mcandre/cowl
https://github.com/mcandre/enlint
https://github.com/mcandre/aspelllint

**Comment by fulldecent** [comment]
That is a good point. I have created separate issues for using our Gem:

 * Use our gem for our example process: #24 
 * Use our gem for our example consumer: #25 
 * Make pull requests for other projects to use our Gem: #26
