### ISSUE TITLE
Update example-consumer to use our gem

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#25]
This is the test case:

    bash example-process/example-process.bash | ruby stat-reader/stat-reader.rb 

We want to get the expected output:

 > WARNING: Go to your room
 > WARNING: Go to your room
 > FAILURE: Go to your room
 > SUMMARY: 2 warnings, 1 failure

Importantly, the findings should be presented in realtime as they are output by the process.

 - [ ] Move `stat-reader` to `example-consumer`
 - [ ] Use our ruby gem
   - [ ] If necessary, propose changes to our Gem to support this incremental reading. We may have to use a different JSON library.
 - [ ] Hard code the output formatting to match the above (issue #26 will introduce a built-in pretty formatting we will use later)
 - [ ] Make it work as expected, including incremental rendering
 - [ ] Add a README.md

**Comment by ilyalyo** [comment]
Added PR https://github.com/fulldecent/structured-acceptance-test/pull/28
I updated stat lib, so now stat reader use local stat library, not public gem, after updating public gem I will change it.

**Comment by fulldecent** [comment]
Ready to update

**Comment by ilyalyo** [comment]
Did you push new version to gem repository?
It still 0.0.1 https://rubygems.org/gems/structured-acceptance-test/versions/0.0.1
Also, can you generate bundle and push it after merging this PR https://github.com/fulldecent/structured-acceptance-test/pull/28
It also has changes in library.

**Comment by ilyalyo** [comment]
Changes merged in this PR https://github.com/fulldecent/structured-acceptance-test/pull/29
After updating gem repository we can close it.

**Comment by fulldecent** [comment]
Published, closing

**Comment by fulldecent** [comment]
Reopening.

Please review all the items in the task list above.

The example consumer is NOT using our gem. See https://github.com/fulldecent/structured-acceptance-test/tree/master/tools/example-consumer/stat-reader there is no Gemfile.

**Comment by ilyalyo** [comment]
Added PR https://github.com/fulldecent/structured-acceptance-test/pull/31
It should be merged only after rubygems will be updated.

**Comment by fulldecent** [comment]
Pushed new ruby gem.

**Comment by ilyalyo** [comment]
I'm apologise, but before closing this issue we need to update gem in rubygems again.
With this changes:
https://github.com/fulldecent/structured-acceptance-test/pull/33
It was a bug with wrong json convertation of Process object.

**Comment by fulldecent** [comment]
Published 0.0.4

**Comment by ilyalyo** [comment]
New version doesn't contain changes from #33. It's same as 0.0.3.

**Comment by fulldecent** [comment]
Republished as 0.0.5

**Comment by ilyalyo** [comment]
Works!
