### ISSUE TITLE
Produce computer program that reads and reports the STAT format

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#6]
An example computer program is produced that reads and reports the above output

It can do any type of reporting with it

Program should be in Ruby and very simple.

**Comment by ilyalyo** [comment]
How this program should report STAT?
Output statistic, like number of findings, or display only some of them.

**Comment by fulldecent** [comment]
Output statistic is good, like number of findings, number of failures, and how many include fixes.
