### ISSUE TITLE
Convert JUnit format

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#8]
Accept format like this:

``` xml
<?xml version='1.0' encoding='UTF-8'?>
<testsuites tests='4' failures='0'>
  <testsuite name='Impostor_Tests.ImpostorGameModel_Tests' tests='3' failures='0'>
    <testcase classname='Impostor_Tests.ImpostorGameModel_Tests' name='testElimanateAPlayer' time='0.067'/>
    <testcase classname='Impostor_Tests.ImpostorGameModel_Tests' name='testGameStatusChangedWhenDoneShowingSecretWords' time='0.001'/>
    <testcase classname='Impostor_Tests.ImpostorGameModel_Tests' name='testStartGameWithSamePlayers' time='0.003'/>
  </testsuite>
  <testsuite name='ImpostorUITests.ImpostorUITests' tests='1' failures='0'>
    <testcase classname='ImpostorUITests.ImpostorUITests' name='testScreenshots' time='31.804'/>
  </testsuite>
</testsuites>
```

And convert to STAT format.

With a script in the tools directory

**Comment by fulldecent** [comment]
This is now part of #18

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/structured-acceptance-test/pull/22
Full jUnit format can be found here: http://help.catchsoftware.com/display/ET/JUnit+Format
For now tool generate process like this: 
"process":{"name":"JUnit"}
and one finding for each testcase, where
rule is the name of testcase
description is a failure message

**Comment by fulldecent** [comment]
Good work!

Please add a very good README.md file for the junit file so people know how to use it.

**Comment by ilyalyo** [comment]
Added PR: https://github.com/fulldecent/structured-acceptance-test/pull/30
