### ISSUE TITLE
Create JSON schema validator

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/structured-acceptance-test#9]
In Ruby, in a new tools directory.

Depends on: #1

**Comment by ilyalyo** [comment]
Add a PR https://github.com/fulldecent/structured-acceptance-test/pull/12

**Comment by ilyalyo** [comment]
Also can you take a look on this: https://github.com/fulldecent/structured-acceptance-test/pull/14
Possible misspeling in docs.
